name: Daily Connpass Event Notification

on:
  schedule:
    # よく使われる時間設定例（JST時間）：
    # - cron: '0 23 * * *'  # UTC 23:00 = JST 8:00（午前8時）
    # - cron: '0 0 * * *'   # UTC 0:00 = JST 9:00（午前9時）- 現在の設定
    # - cron: '30 0 * * *'  # UTC 0:30 = JST 9:30（午前9時30分）
    # - cron: '0 1 * * *'   # UTC 1:00 = JST 10:00（午前10時）
    # - cron: '0 2 * * *'   # UTC 2:00 = JST 11:00（午前11時）
    # - cron: '0 3 * * *'   # UTC 3:00 = JST 12:00（午後12時）
    # - cron: '0 9 * * *'   # UTC 9:00 = JST 18:00（午後6時）
    # - cron: '0 12 * * *'  # UTC 12:00 = JST 21:00（午後9時）
    # - cron: '0 15 * * *'  # UTC 15:00 = JST 0:00（深夜0時）
    #
    # 複数回実行する場合：
    # - cron: '0 0 * * *'   # 毎日午前9時
    # - cron: '0 18 * * *'  # 毎日午前3時（前日UTC 18:00）
    #
    # 週次実行の場合：
    # - cron: '0 0 * * 1'   # 毎週月曜日午前9時
    # - cron: '0 0 * * 5'   # 毎週金曜日午前9時
    #
    # 月次実行の場合：
    # - cron: '0 0 1 * *'   # 毎月1日午前9時
    - cron: '0 0 * * *'  # UTC 0:00 = JST 9:00（午前9時）
  workflow_dispatch:  # 手動実行も可能

jobs:
  notify-events:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
        
    - name: Run notification script
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        python3 main.py
        
    - name: Commit and push notified IDs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add notified_event_ids.txt
        git commit -m "Update notified event IDs" || echo "No changes to commit"
        git push 