name: Connpass Event Notifier

on:
  workflow_dispatch: # 手動実行を許可
  schedule:
    # 毎日午前9時(JST)に実行 (UTCでは0時)
    - cron: '0 0 * * *'

# ここにパーミッションを追加します
permissions:
  contents: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Pythonスクリプトを実行
      - name: Run script
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py

      # 5. 変更されたファイルをリポジトリにコミット
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add notified_event_ids.txt
          # 変更があった場合のみコミット
          git diff --quiet && git diff --staged --quiet || git commit -m "Update notified events list"
          git push
